name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Add Python to PATH
        run: echo "$(rye show python-path | head -n 1 | xargs dirname | xargs dirname)/bin" >> $GITHUB_PATH

      - name: Cache Rye
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/rye
            ~/.rye
          key: ${{ runner.os }}-rye-${{ hashFiles('**/pyproject.toml', '**/pyproject.lock') }}
          restore-keys: |
            ${{ runner.os }}-rye-

      - name: Sync dependencies
        run: rye sync --no-dev

      - name: Lint & Format (Ruff)
        run: rye run ruff check .

      - name: Run tests
        run: rye run test
